import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

TOOL = Path(__file__).parent.parent / "tools" / "guide_text.py"
DRAFT = """# How to read the map (draft, revision 7: test)

## Part 2: the text players read

### How to read the map

The past never changes. **[C1]**

#### Save point = commit

**Figure `commit`:** one staged file, then `git commit`.

**Caption:** A **commit** is a snapshot. **[K1: C2]**

*The picture: a ring with a solid core.*

- A commit is a snapshot of every tracked file,
  exactly as staged. **[C2]**

#### Coming later: undoing

**Caption:** A preview. **[K10]**

- `git revert` adds a commit. **[C26] [C27]**

---

## Part 3: claims register
"""
PAGE = """const TimeGuide = (function () {
  /* Generated by tools/guide_text.py, revision 1. */
  const INTRO = "old";

  const SECTIONS = [
    {
      points: [
        "old",
      ],
    },
  ];

  return { SECTIONS };
})();
"""


def tool() -> ModuleType:
    """
    Load ``tools/guide_text.py``, which is a script and not part of the package.

    Returns
    -------
    ModuleType
        The script as a module, without running its command line.
    """
    spec = importlib.util.spec_from_file_location("guide_text", TOOL)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_pages_guide_text_is_the_drafts_part_2_word_for_word() -> None:
    result = subprocess.run([sys.executable, str(TOOL), "--check"], capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stderr


def test_each_section_keeps_its_figure_id_caption_picture_and_points_without_claim_tags() -> None:
    intro, sections = tool().text(DRAFT)
    assert intro == "The past never changes."
    assert sections == [
        {
            "id": "commit",
            "title": "Save point = commit",
            "mark": "commit",
            "caption": "A **commit** is a snapshot.",
            "picture": "The picture: a ring with a solid core.",
            "points": ["A commit is a snapshot of every tracked file, exactly as staged."],
        },
        {
            "id": "later",
            "title": "Coming later: undoing",
            "mark": None,
            "caption": "A preview.",
            "picture": None,
            "points": ["`git revert` adds a commit."],
        },
    ]


def test_the_text_replaces_only_the_generated_block_and_names_the_drafts_revision() -> None:
    page = tool().with_text(PAGE, DRAFT)
    assert page.startswith("const TimeGuide = (function () {\n  /* Generated by tools/guide_text.py")
    assert "revision 7" in page and '"The past never changes."' in page and '"old"' not in page
    assert page.endswith("  ];\n\n  return { SECTIONS };\n})();\n")
    assert tool().with_text(page, DRAFT) == page


def test_a_paragraph_the_page_has_no_place_for_is_refused() -> None:
    draft = DRAFT.replace("*The picture: a ring with a solid core.*", "A stray paragraph.")
    with pytest.raises(ValueError, match="A stray paragraph"):
        tool().text(draft)
