"""
Write the map guide's text into the page, word for word from its draft.

``uv run python tools/guide_text.py`` reads Part 2 of ``docs/drafts/map-guide.md`` and rewrites
the INTRO and SECTIONS of ``src/firstcommit/web/static/theme-time-guide.js``, without the claim
tags. With ``--check`` it changes nothing and fails when the page's text differs from the draft.
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DRAFT = ROOT / "docs" / "drafts" / "map-guide.md"
PAGE = ROOT / "src" / "firstcommit" / "web" / "static" / "theme-time-guide.js"

PART_2 = "## Part 2: the text players read"
START = "  /* Generated by tools/guide_text.py"
END = "\n  ];\n"
NO_FIGURE = "later"
"""The id of the one section with no figure: the preview of later chapters."""

MARKS: dict[str, str | None] = {
    "commit": "commit",
    "parents": "line",
    "branch": "branch",
    "now": "now",
    "detached": "now",
    "merge": "merge",
    "tag": "tag",
    "archive": "archive",
    "seen": "remote",
    NO_FIGURE: None,
}
"""The small picture (TimeTheme.mark) beside each section's title."""

# A claim tag ends a sentence: **[C5]**, **[K4: C12, C15]** or **[C16] [C32] [M7]**.
CLAIM_TAGS = re.compile(r"\s*\*\*\[[^*]*\]\*\*$")
FIGURE = re.compile(r"\*\*Figure `(\w+)`:\*\*")
REVISION = re.compile(r"revision (\d+)")


def literal(value: Any) -> str:
    """
    Write a JSON value as a JavaScript literal, keeping non-ASCII characters as they are.

    Parameters
    ----------
    value : Any
        A string, a list of strings or None.

    Returns
    -------
    str
        The literal.
    """
    return json.dumps(value, ensure_ascii=False)


def paragraphs(block: str) -> list[str]:
    """
    Split Markdown into its paragraphs and list items, each joined onto one line.

    Parameters
    ----------
    block : str
        Markdown text.

    Returns
    -------
    list[str]
        The paragraphs and ``- `` items in order, without blank ones.
    """
    items: list[str] = []
    for raw in block.split("\n"):
        line = raw.rstrip()
        if not line:
            items.append("")
        elif line.startswith("- ") or not items or items[-1] == "":
            items.append(line)
        else:
            items[-1] += " " + line.strip()
    return [item for item in items if item]


def section(heading: str) -> dict[str, Any]:
    """
    Read one ``####`` section of Part 2 into a SECTIONS entry.

    Parameters
    ----------
    heading : str
        The section from its title line to the next section.

    Returns
    -------
    dict[str, Any]
        id, title, mark, caption, picture (None when the section has none) and points.

    Raises
    ------
    ValueError
        If the section holds a paragraph that is none of a Figure line, a caption, an italic
        picture line or a list item.
    """
    title, body = heading.split("\n", 1)
    entry: dict[str, Any] = {"id": NO_FIGURE, "title": title.strip(), "caption": None, "picture": None, "points": []}
    for item in paragraphs(body):
        figure = FIGURE.match(item)
        if figure:
            entry["id"] = figure.group(1)
        elif item.startswith("**Caption:** "):
            entry["caption"] = CLAIM_TAGS.sub("", item.removeprefix("**Caption:** "))
        elif item.startswith("*") and item.endswith("*"):
            entry["picture"] = item[1:-1]
        elif item.startswith("- "):
            entry["points"].append(CLAIM_TAGS.sub("", item[2:]))
        else:
            raise ValueError(f"no place on the page for this paragraph in {entry['title']!r}: {item[:60]}")
    order = ["id", "title", "mark", "caption", "picture", "points"]
    return {key: MARKS[entry["id"]] if key == "mark" else entry[key] for key in order}


def text(draft: str) -> tuple[str, list[dict[str, Any]]]:
    """
    Read the text players see from the draft's Part 2.

    Parameters
    ----------
    draft : str
        The whole draft, ``docs/drafts/map-guide.md``.

    Returns
    -------
    tuple[str, list[dict[str, Any]]]
        The intro and the sections, in order, without claim tags.
    """
    part = draft.split(PART_2, 1)[1].split("\n---\n", 1)[0]
    head, *headings = re.split(r"^#### ", part, flags=re.MULTILINE)
    intro = CLAIM_TAGS.sub("", paragraphs(head.split("### How to read the map", 1)[1])[0])
    return intro, [section(heading) for heading in headings]


def javascript(draft: str) -> str:
    """
    Write the draft's Part 2 as the page's INTRO and SECTIONS.

    Parameters
    ----------
    draft : str
        The whole draft.

    Returns
    -------
    str
        The block, from its "Generated" comment to the line that closes SECTIONS.

    Raises
    ------
    ValueError
        If the draft's title does not give its revision.
    """
    revision = REVISION.search(draft.split("\n", 1)[0])
    if revision is None:
        raise ValueError("the draft's title does not give its revision")
    intro, sections = text(draft)
    lines = [
        f"{START} from docs/drafts/map-guide.md, Part 2, revision {revision.group(1)}, without its",
        "     claim tags. Change the draft, then run the tool. */",
        f"  const INTRO = {literal(intro)};",
        "",
        "  const SECTIONS = [",
    ]
    for entry in sections:
        lines.append("    {")
        lines += [f"      {key}: {literal(value)}," for key, value in entry.items() if key != "points"]
        lines += ["      points: [", *[f"        {literal(point)}," for point in entry["points"]], "      ],"]
        lines.append("    },")
    lines.append("  ];")
    return "\n".join(lines)


def with_text(page: str, draft: str) -> str:
    """
    Give the page with its generated block replaced by the draft's text.

    Parameters
    ----------
    page : str
        ``theme-time-guide.js``.
    draft : str
        The whole draft.

    Returns
    -------
    str
        The page, changed only between the "Generated" comment and the end of SECTIONS.

    Raises
    ------
    ValueError
        If the page has no generated block.
    """
    start = page.find(START)
    end = page.find(END, start)
    if start < 0 or end < 0:
        raise ValueError("the page has no block generated by tools/guide_text.py")
    return page[:start] + javascript(draft) + page[end + len("\n  ];") :]


def main(argv: list[str]) -> int:
    """
    Rewrite the page's guide text from the draft, or check that it is current.

    Parameters
    ----------
    argv : list[str]
        The command-line arguments, without the program name.

    Returns
    -------
    int
        0 when the page was written or is current, 1 when ``--check`` found it out of date.
    """
    parser = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    parser.add_argument(
        "--check", action="store_true", help="change nothing; fail when the page differs from the draft"
    )
    check = parser.parse_args(argv).check
    page = PAGE.read_text()
    updated = with_text(page, DRAFT.read_text())
    status = 0
    if check and updated != page:
        print(
            f"{PAGE.relative_to(ROOT)} differs from {DRAFT.relative_to(ROOT)}: run tools/guide_text.py", file=sys.stderr
        )
        status = 1
    elif not check:
        PAGE.write_text(updated)
    return status


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
